### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by Chen-Gary** [Chen-Gary/MAPF#1]
**问题：**
现在是每个robot plan path一次，就global update一次，完全是sequential；
应该改成，所有robot report一次intended nextPos，然后global检查collision

**计划：**
就先写成这样吧，这个simulation platform只能做到逻辑上等同于我的算法，
performance不会好，因为并没做到parallel

**Comment by Chen-Gary** [comment]
## 相机参数

大地图 76 * 48

Position
29, 10, 22

Size
28

---

小地图

Position
6.5, 10, 7

Size
8

**Comment by Chen-Gary** [comment]
不带heatmap的版本算是写完了，会有deadlock

希望heatmap能解决deadlock问题

**Comment by Chen-Gary** [comment]
【这些数据已经没用了】
实验

heatmap参数		timestamps
100				325
6				273
1				279
0.2				deadlock
no				deadlock

**Comment by Chen-Gary** [comment]
## 算法
- [ ] A*为什么会fail？
- [ ] 稍微做一点冲突化解
- [ ] *统计conflict数量，作为一个新的量化指标（不好搞）
- [ ] *接任务时，接就近的任务，而不是直接按顺序assign任务

## UI
参考海柔创新、极智嘉？
- [ ] 标记待接收任务的地点（e.g. 闪一下）

## 测试/实验用例
- [ ] 货架只有2排
- [ ] 过道有3排
- [ ] 把货架长度拉长，把过道变得“狭长”（为了更好地体现heatmap的作用）
- [ ] 终点为固定的分拣站（UI上，当robot扛着货物，把它显示出来）
